apiVersion: v1
kind: Pod
metadata:
  name: fsadmin
  namespace: fsadmin
spec:
  containers:
  - name: main
    image: ghcr.io/lsst-sqre/idf-fsadmin:latest
    args: [ "tail", "-f", "/dev/null" ]
    volumeMounts:
    - mountPath: /mnt/home
      name: home
    - mountPath: /mnt/rubin
      name: rubin
    - mountPath: /mnt/deleted-sundays
      name: deleted-sundays
    - mountPath: /mnt/firefly
      name: firefly
  volumes:
  - name: home
    nfs:
      path: /home-share
      server: 10.231.144.5
  - name: rubin
    nfs:
      path: /rubin-share
      server: 10.231.144.4
  - name: deleted-sundays
    nfs:
      path: /deleted-sundays-share
      server: 10.231.144.5
  - name: firefly
    nfs:
      path: /firefly-share
      server: 10.231.144.4
