name: CI

"on":
  merge_group: {}
  pull_request: {}
  push:
    branches-ignore:
      # These should always correspond to pull requests, so ignore them for
      # the push trigger and let them be triggered by the pull_request
      # trigger, avoiding running the workflow twice.  This is a minor
      # optimization so there's no need to ensure this is comprehensive.
      - "dependabot/**"
      - "gh-readonly-queue/**"
      - "renovate/**"
      - "tickets/**"
      - "u/**"
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    # Only do Docker builds of tagged releases and pull requests from ticket
    # branches. This will still trigger on pull requests from untrusted
    # repositories whose branch names match our tickets/* branch convention,
    # but in this case the build will fail with an error since the secret
    # won't be set.
    if: >
      startsWith(github.ref, 'refs/tags/')
      || startsWith(github.head_ref, 'tickets/')

    steps:
      - uses: actions/checkout@v4
        with:
          # Full history is required for setuptools_scm versioning.
          fetch-depth: 0
      - uses: lsst-sqre/build-and-push-to-ghcr@v1
        id: build-idf-fsadmin
        with:
          dockerfile: Dockerfile
          image: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Google Artifact Repository
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: "_json_key_base64"
          password: ${{ secrets.GAR_PUSH_TOKEN }}

      - name: Docker meta
        id: idf-fsadmin-meta
        uses: docker/metadata-action@v5
        with:
          images: |
            us-central1-docker.pkg.dev/rubin-shared-services-71ec/sciplat/idf-fsadmin
          tags: |
            type=raw,${{ steps.build-idf-fsadmin.outputs.tag }}

      - name: Build and push idf-fsadmin to GAR
        uses: docker/build-push-action@v6
        with:
          context: "."
          file: Dockerfile
          push: "true"
          tags: ${{ steps.idf-fsadmin-meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Report result
        run: |
          echo Pushed ghcr.io/${{ github.repository }}:${{ steps.build-inithome.outputs.tag }}
